const ERROR_CODE_VALIDATION = 400;
const ERROR_CODE_AVAILABILITY = 404;
const ERROR_CODE_DEFAULT = 500;
const ERROR_CODE_OWNERS = 403;

module.exports = {
  ERROR_CODE_VALIDATION, ERROR_CODE_AVAILABILITY, ERROR_CODE_DEFAULT, ERROR_CODE_OWNERS,
};
